### ISSUE TITLE
Cannot rotate display (ctp40) in pi4 running octopi

### ISSUE THREAD

**Issue by chasrobertson** [FYSETC/FYSETC-CTP40#6]
Hi,
I have installed all the drivers and the display is running in portrait mode, but when I try to run ctp40-rotate, I get the reply:
This rotate utility only works with the Raspberry PI OS desktop version. You need to set a DISPLAY variable. Try: DISPLAY=:0.0 stp40-rotate  <orientation>.
I presume that it should be DISPLAY=0:0 rather than what is shown on the screen.
When I try this out I get an error :- 
Traceback (most recent call last):
File "<stdin>", line 3, in <module>
Import error: No Module named in screenlayout. Failed to set display orientation. Make sure you're running Raspberry Pi OS Desktop on a Pi 4.

Any ideas how I can get this to work, as Octopi is better in landscape mode,
Regards
Chas.Robertson.

**Comment by SergPanin** [comment]
Dont rotate (OctoPi)

pi@raspberrypi:~ $ ctp40-rotate left
This rotate utility only works with the Raspberry Pi OS desktop version.
You need to set a DISPLAY variable.
Try: DISPLAY=:0.0 ctp40-rotate <orientation>

DISPLAY=:0.0 ctp40-rotate left
This rotate utility only works with the Raspberry Pi OS desktop version.
Rotating display
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named screenlayout
Failed to set display orientation. Make sure you're running Raspberry Pi OS desktop on a Pi 4.

**Comment by chasrobertson** [comment]
Have tried with a fresh installation of raspberry pi with the same result! There appear to be problems with the latest version (32 bit) Sent from my Galaxy<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: SergPanin ***@***.***> </div><div>Date: 05/09/2021  17:17  (GMT+00:00) </div><div>To: FYSETC/FYSETC-CTP40 ***@***.***> </div><div>Cc: Chas Robertson ***@***.***>, Chas Robertson ***@***.***>, Author ***@***.***> </div><div>Subject: Re: [FYSETC/FYSETC-CTP40] Cannot rotate display (ctp40) in pi4 running octopi (#6) </div><div>
</div>
>>> "SergPanin" ***@***.***> 09/05/2021 17:18 >>>
Dont rotate (OctoPi)

***@***.***:~ $ ctp40-rotate left
This rotate utility only works with the Raspberry Pi OS desktop version.
You need to set a DISPLAY variable.
Try: DISPLAY=:0.0 ctp40-rotate <orientation>

DISPLAY=:0.0 ctp40-rotate left
This rotate utility only works with the Raspberry Pi OS desktop version.
Rotating display
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named screenlayout
Failed to set display orientation. Make sure you're running Raspberry Pi OS desktop on a Pi 4.
